@startuml

start

if (Recruiter contacts me LinkedIn      ) then (Contact Invite      )
    :Press Ignore;
    :Block user;
else (InMail)
    if (Works for recruitment agency?       ) then (No)
      :In house recruiter   ;
      if (Did recruiter actually read profile?          ) then (No)
         :Terse response;
         if (Recruiter loses his shit?      ) then (Yes  )
            :Taunt recruiter;
            :Block user;
         else (No)
            :Delete conversation;
         endif
      else (Yes)
        if (Satisfied at current job        ) then (Yes     )
          :Polite refusal;
          :Archive conversation;
        else (No)
            if (Is job offer interesting?       ) then (Yes)
                :Start conversation;
                :Positive outcome for recruiter     ;
                stop;
            else (No)
                :Polite refusal;
                :Archive conversation;
            endif
        endif
      endif
    else (Yes)
        :Block user;
    endif
endif
:Negative outcome for recruiter     ;
stop

@enduml
